DROP TABLE IF EXISTS users; CREATE TABLE users (uid INTEGER PRIMARY KEY AUTOINCREMENT, nationality TEXT, gender TEXT);

DROP TABLE IF EXISTS dates; CREATE TABLE dates (did INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, address TEXT, password TEXT, phone NUMBER, pic TEXT, created_at_d REAL DEFAULT CURRENT_TIMESTAMP);